- type: replace
  path: /instance_groups/name=victoria-metrics/jobs/name=victoria-metrics/properties/victoria-metrics?/tls?
  value:
    ca: ((tls_victoria_metrics.ca))
    certificate: ((tls_victoria_metrics.certificate))
    private_key: ((tls_victoria_metrics.private_key))

- type: replace
  path: /variables/-
  value:
    name: victoria_metrics_ca
    type: certificate
    options:
      is_ca: true
      common_name: ca

- type: replace
  path: /variables/-
  value:
    name: tls_victoria_metrics
    type: certificate
    options:
      ca: victoria_metrics_ca
      common_name: victoria-metrics.default.victoria-metrics.bosh
      alternative_names:
      - "victoria-metrics.default.victoria-metrics.bosh"
      - "*.victoria-metrics.default.victoria-metrics.bosh"
      extended_key_usage:
      - server_auth
      - client_auth
